# Go cross compiler (xgo): Go 1.16.x
# Copyright (c) 2020 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM suburbandad/xgo-1.16.6

MAINTAINER Péter Szilágyi <peterke@gmail.com>
