# Go cross compiler (xgo): Go 1.16.x
# Copyright (c) 2020 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM wealdtech/xgo-1.16.7

MAINTAINER Péter Szilágyi <peterke@gmail.com>
