# Go cross compiler (xgo): Go 1.13.x
# Copyright (c) 2020 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM suburbandad/xgo-1.14

MAINTAINER Péter Szilágyi <peterke@gmail.com>
