# Go cross compiler (xgo): Go 1.17.x
# Copyright (c) 2020 Péter Szilágyi. All rights reserved.
#
# Released under the MIT license.

FROM wealdtech/xgo-1.17.1

MAINTAINER Péter Szilágyi <peterke@gmail.com>
